<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks Condition="'$(UseSkiaSharpShim)' != 'true'">$(AvsCurrentTargetFramework);$(AvsLegacyTargetFrameworks)</TargetFrameworks>
    <TargetFrameworks Condition="'$(UseSkiaSharpShim)' == 'true'">$(AvsCurrentTargetFramework)</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableRuntimeMarshalling>true</EnableRuntimeMarshalling>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\packages\Avalonia\Avalonia.csproj" />
    <ProjectReference Include="..\..\Skia\Avalonia.Skia\Avalonia.Skia.csproj"
                      Condition="'$(UseSkiaSharpShim)' != 'true'" />
    <ProjectReference Include="..\..\Skia\Avalonia.SkiaShim\Avalonia.SkiaShim.csproj"
                      Condition="'$(UseSkiaSharpShim)' == 'true'" />
    <Compile Include="..\..\Shared\RawEventGrouping.cs" />
  </ItemGroup>
  <Import Project="..\..\..\build\TrimmingEnable.props" />
  <Import Project="..\..\..\build\NullableEnable.props" />
</Project>
