<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(AvsCurrentTargetFramework)</TargetFrameworks>
    <AssemblyName>Avalonia.Skia</AssemblyName>
    <RootNamespace>Avalonia.Skia</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <ProGpuSourceRoot Condition="'$(ProGpuSourceRoot)' == ''">$(MSBuildThisFileDirectory)..\..\..\..\ProGPU</ProGpuSourceRoot>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\NoiseAsset_256X256_PNG.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\packages\Avalonia\Avalonia.csproj" />
    <ProjectReference Include="$(ProGpuSourceRoot)\src\SkiaSharp\SkiaSharp.csproj" />
  </ItemGroup>

  <Import Project="..\..\..\build\HarfBuzzSharp.props" />
  <Import Project="..\..\..\build\DevAnalyzers.props" />
  <Import Project="..\..\..\build\TrimmingEnable.props" />
  <Import Project="..\..\..\build\NullableEnable.props" />

  <ItemGroup Label="InternalsVisibleTo">
    <InternalsVisibleTo Include="Avalonia.SkiaShim.RenderTests, PublicKey=$(AvaloniaPublicKey)" />
    <InternalsVisibleTo Include="Avalonia.SkiaShim.UnitTests, PublicKey=$(AvaloniaPublicKey)" />
    <InternalsVisibleTo Include="Avalonia.Benchmarks, PublicKey=$(AvaloniaPublicKey)" />
  </ItemGroup>
</Project>
