#!/usr/bin/env python3
"""Complete the token contract and correct issues found by compiled-XAML CI."""
from pathlib import Path
from xml.etree import ElementTree as ET
import json
import re
from generate_10_tokens import commit, TYPES

ROOT = Path(__file__).resolve().parents[2]
THEME = ROOT / 'src/Avalonia.Themes.MacOS'
X = '{http://schemas.microsoft.com/winfx/2006/xaml}'


def main():
    path = THEME / 'Tokens/Semantic.xaml'
    text = path.read_text()
    if '<TimeSpan ' in text:
        text = text.replace('<ResourceDictionary ', '<ResourceDictionary xmlns:sys="clr-namespace:System;assembly=System.Runtime" ', 1)
        text = text.replace('<TimeSpan ', '<sys:TimeSpan ').replace('</TimeSpan>', '</sys:TimeSpan>')
        path.write_text(text)
    # Compact must not exceed regular dimensions, nor use a different value type.
    path = THEME / 'DensityStyles/Compact.xaml'
    text = path.read_text().replace('<x:Double x:Key="MacOS.CommandBarButtonMinHeight">32</x:Double>',
        '<x:Double x:Key="MacOS.CommandBarButtonMinHeight">26</x:Double>')
    text = text.replace('<Thickness x:Key="MacOS.ComboBoxItemThemePadding">11,5,11,7</Thickness>',
        '<Thickness x:Key="MacOS.ComboBoxItemThemePadding">8,3</Thickness>')
    path.write_text(text)
    manifest_path = THEME / 'Tokens/token-manifest.json'
    manifest = json.loads(manifest_path.read_text())
    entries = {item['key']: item for item in manifest['tokens']}
    extra = {}
    for path in sorted(THEME.rglob('*.xaml')):
        for node in ET.parse(path).iter():
            key = node.get(X + 'Key', '')
            kind = node.tag.rsplit('}', 1)[-1]
            if not key.startswith('MacOS.') or kind not in TYPES:
                continue
            if key not in entries:
                extra[key] = kind
                entries[key] = {'key': key, 'legacyKey': None, 'type': kind, 'sources': [], 'baselineDefinitions': []}
            entry = entries[key]
            origin = str(path.relative_to(THEME))
            if origin not in entry['sources']:
                entry['sources'].append(origin)
    path = THEME / 'MacOSTokens.g.cs'
    path.write_text(path.read_text().replace('public static class MacOSTokens', 'public static partial class MacOSTokens'))
    extra_path = THEME / 'MacOSTokens.Semantic.g.cs'
    if extra or not extra_path.exists():
        # Include all non-legacy entries on subsequent runs for reproducibility.
        extra = {key: entry['type'] for key, entry in entries.items() if entry['legacyKey'] is None}
        code = ['// <auto-generated />', '#nullable enable', 'namespace Avalonia.Themes.MacOS;', '',
                'public static partial class MacOSTokens', '{']
        for key, kind in sorted(extra.items()):
            identifier = re.sub(r'\W', '_', key.removeprefix('MacOS.'))
            code += [f'    /// <summary>Gets the {key} token.</summary>',
                     f'    public static readonly MacOSToken<{TYPES[kind]}> {identifier} = new("{key}");']
        code.append('}')
        extra_path.write_text('\n'.join(code) + '\n')
    manifest['tokens'] = sorted(entries.values(), key=lambda x: x['key'])
    manifest_path.write_text(json.dumps(manifest, indent=2) + '\n')
    commit('fix(macos): resolve System.TimeSpan tokens and expose all semantic keys', 'src/Avalonia.Themes.MacOS')

if __name__ == '__main__':
    main()
