#!/usr/bin/env python3
"""Migrate existing visual resources to public MacOS design tokens.
Emitted source is committed; this is not a package build-time dependency.
"""
from pathlib import Path
from collections import defaultdict
from xml.etree import ElementTree as ET
import json
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[2]
THEME = ROOT / 'src/Avalonia.Themes.MacOS'
X = '{http://schemas.microsoft.com/winfx/2006/xaml}'
TYPES = {
    'Double': 'double', 'Int32': 'int', 'Boolean': 'bool',
    'Color': 'global::Avalonia.Media.Color',
    'SolidColorBrush': 'global::Avalonia.Media.IBrush',
    'Thickness': 'global::Avalonia.Thickness',
    'CornerRadius': 'global::Avalonia.CornerRadius',
    'FontFamily': 'global::Avalonia.Media.FontFamily',
    'FontWeight': 'global::Avalonia.Media.FontWeight',
    'VisualBrush': 'global::Avalonia.Media.IBrush',
    'PlacementMode': 'global::Avalonia.Controls.PlacementMode',
    'GridLength': 'global::Avalonia.Controls.GridLength',
    'TimeSpan': 'global::System.TimeSpan',
    'TransformOperations': 'global::Avalonia.Media.Transformation.TransformOperations',
}


def commit(message, *paths):
    if '--no-commit' in sys.argv:
        return
    subprocess.run(['git', 'add', '--', *paths], cwd=ROOT, check=True)
    result = subprocess.run(['git', 'diff', '--cached', '--quiet'], cwd=ROOT)
    if result.returncode == 1:
        subprocess.run(['git', 'commit', '-m', message], cwd=ROOT, check=True)
    elif result.returncode:
        raise RuntimeError('git diff failed')


def generate():
    manifest = THEME / 'Tokens/token-manifest.json'
    if manifest.exists():
        return
    resources, aliases = {}, {}
    origins, defaults = defaultdict(set), defaultdict(list)
    controls = []
    for path in sorted(THEME.rglob('*.xaml')):
        for node in ET.parse(path).iter():
            tag = node.tag.rsplit('}', 1)[-1]
            key = node.get(X + 'Key', '')
            if key.startswith('{x:Type '):
                controls.append({'type': key[8:-1], 'source': str(path.relative_to(THEME))})
            if not key or key.startswith('{'):
                continue
            if tag in TYPES:
                resources[key] = tag
            elif tag == 'StaticResource':
                aliases[key] = node.get('ResourceKey')
            origins[key].add(str(path.relative_to(THEME)))
            if tag in TYPES or tag == 'StaticResource':
                defaults[key].append({'type': tag, 'value': (node.text or '').strip(), 'attributes': dict(node.attrib)})
    for _ in range(len(aliases) + 1):
        changed = False
        for key, target in aliases.items():
            if key not in resources and target in resources:
                resources[key] = resources[target]
                changed = True
        if not changed:
            break
    for suffix in ('', 'Dark1', 'Dark2', 'Dark3', 'Light1', 'Light2', 'Light3'):
        key = 'SystemAccentColor' + suffix
        resources[key] = 'Color'
        origins[key].add('Accents/SystemAccentColors.cs')
    key_map = {key: 'MacOS.' + key for key in resources}

    def resource_ref(match):
        kind, key = match.groups()
        return '{DynamicResource ' + key_map[key] + '}' if key in key_map else match.group(0)

    for path in sorted(THEME.rglob('*')):
        if path.suffix not in ('.xaml', '.cs'):
            continue
        text = path.read_text(encoding='utf-8-sig')
        if path.suffix == '.xaml':
            text = re.sub(r'\{(StaticResource|DynamicResource)\s+([^{}]+)\}', resource_ref, text)
            text = re.sub(r'(x:Key|ResourceKey)="([^"]+)"', lambda m: m[1] + '="' + key_map.get(m[2], m[2]) + '"', text)
        else:
            text = re.sub(r'"([^"\n]+)"', lambda m: '"' + key_map.get(m[1], m[1]) + '"', text)
        path.write_text(text, encoding='utf-8')

    generated = ['// <auto-generated />', '#nullable enable', 'namespace Avalonia.Themes.MacOS;', '',
                 '/// <summary>Strongly typed keys for every theme visual resource.</summary>', 'public static class MacOSTokens', '{']
    identifiers, entries = set(), []
    for key, kind in sorted(resources.items()):
        identifier = re.sub(r'\W', '_', key)
        if identifier[0].isdigit():
            identifier = '_' + identifier
        if identifier in identifiers:
            raise ValueError('Duplicate token identifier: ' + identifier)
        identifiers.add(identifier)
        public_key = key_map[key]
        generated.append('    /// <summary>Overrides ' + key + '.</summary>')
        generated.append(f'    public static readonly MacOSToken<{TYPES[kind]}> {identifier} = new("{public_key}");')
        entries.append({'key': public_key, 'legacyKey': key, 'type': kind, 'sources': sorted(origins[key]), 'baselineDefinitions': defaults[key]})
    generated.append('}')
    (THEME / 'MacOSTokens.g.cs').write_text('\n'.join(generated) + '\n')
    (THEME / 'MacOSToken.cs').write_text('''namespace Avalonia.Themes.MacOS;

/// <summary>A strongly typed, stable design-token resource key.</summary>
/// <typeparam name="T">The resource value type.</typeparam>
public sealed class MacOSToken<T>
{
    internal MacOSToken(string key) => Key = key;

    /// <summary>Gets the XAML resource key.</summary>
    public string Key { get; }

    /// <inheritdoc />
    public override string ToString() => Key;
}
''')
    aliases_cs = ['// <auto-generated />', '#nullable enable', 'using System;', 'using System.Collections.Generic;',
                  'namespace Avalonia.Themes.MacOS;', 'internal static class MacOSTokenAliases', '{',
                  '    private static readonly HashSet<string> s_keys = new(StringComparer.Ordinal)', '    {']
    aliases_cs.extend('        "' + key + '",' for key in sorted(resources))
    aliases_cs.extend(['    };', '', '    public static object Normalize(object key) =>',
                      '        key is string text && s_keys.Contains(text) ? "MacOS." + text : key;', '}'])
    (THEME / 'MacOSTokenAliases.g.cs').write_text('\n'.join(aliases_cs) + '\n')
    path = THEME / 'MacOSTheme.xaml.cs'
    text = path.read_text().replace('public class MacOSTheme', 'public partial class MacOSTheme')
    text = text.replace('AvaloniaXamlLoader.Load(sp, this);', 'AvaloniaXamlLoader.Load(sp, this);\n            Resources.MergedDictionaries.Add(Tokens);')
    text = text.replace('// DensityStyle dictionary should be checked first',
                        'key = MacOSTokenAliases.Normalize(key);\n            if (Tokens.TryGetResource(key, theme, out value))\n                return true;\n\n            // DensityStyle dictionary should be checked first')
    path.write_text(text)
    (THEME / 'MacOSTheme.Tokens.cs').write_text('''using System;
using Avalonia.Controls;
using Avalonia.Styling;
using Avalonia.Threading;

namespace Avalonia.Themes.MacOS;

public partial class MacOSTheme
{
    /// <summary>Gets application overrides, including per-variant dictionaries.
    /// Use this dictionary rather than mutating shared default brushes.</summary>
    public ResourceDictionary Tokens { get; } = new();

    /// <summary>Overrides a design token. Call on the UI thread.</summary>
    /// <typeparam name="T">The resource value type.</typeparam>
    /// <param name="token">A key from <see cref="MacOSTokens"/>.</param>
    /// <param name="value">The replacement value.</param>
    /// <param name="variant">Optional light/dark/custom variant; null overrides all variants.</param>
    public void SetToken<T>(MacOSToken<T> token, T value, ThemeVariant? variant = null)
    {
        Dispatcher.UIThread.VerifyAccess();
        ArgumentNullException.ThrowIfNull(token);
        ArgumentNullException.ThrowIfNull(value);
        if (variant is null)
        {
            Tokens[token.Key] = value;
        }
        else
        {
            if (!Tokens.ThemeDictionaries.TryGetValue(variant, out var provider))
            {
                provider = new ResourceDictionary();
                Tokens.ThemeDictionaries.Add(variant, provider);
            }
            if (provider is not ResourceDictionary dictionary)
                throw new InvalidOperationException("The token variant must be a ResourceDictionary.");
            dictionary[token.Key] = value;
        }
    }

    /// <summary>Removes an override and restores the underlying theme resource.</summary>
    /// <typeparam name="T">The resource value type.</typeparam>
    /// <param name="token">The token to reset.</param>
    /// <param name="variant">The variant originally passed to SetToken.</param>
    /// <returns>Whether an override was removed.</returns>
    public bool ResetToken<T>(MacOSToken<T> token, ThemeVariant? variant = null)
    {
        Dispatcher.UIThread.VerifyAccess();
        ArgumentNullException.ThrowIfNull(token);
        if (variant is null)
            return Tokens.Remove(token.Key);
        return Tokens.ThemeDictionaries.TryGetValue(variant, out var provider)
            && provider is ResourceDictionary dictionary && dictionary.Remove(token.Key);
    }
}
''')
    manifest.parent.mkdir(exist_ok=True)
    manifest.write_text(json.dumps({'schemaVersion': 1, 'tokens': entries, 'controls': controls}, indent=2) + '\n')
    docs = ROOT / 'docs/themes/macos26'
    docs.mkdir(parents=True, exist_ok=True)
    lines = ['# Control template coverage', '', 'Every implicit control theme from the copied Fluent baseline is retained.',
             'Template presence is not a claim of visual or interaction certification.', '', '| Control | Source |', '| --- | --- |']
    lines += [f'| `{c["type"]}` | `{c["source"]}` |' for c in sorted(controls, key=lambda x: x['type'])]
    (docs / 'CONTROL-COVERAGE.md').write_text('\n'.join(lines) + '\n')
    commit('feat(macos): expose complete typed design-token inventory and live overrides', 'src/Avalonia.Themes.MacOS', 'docs/themes/macos26')
    print(f'Migrated {len(entries)} visual tokens; retained {len(controls)} implicit control themes.')

if __name__ == '__main__':
    generate()
