#!/usr/bin/env python3
"""Regenerate public typed token keys from checked-in XAML, or verify with --check.

No application build depends on Python. Existing key names and legacy aliases are
preserved; unsupported resource types and conflicting identifiers fail explicitly.
"""
from pathlib import Path
from xml.etree import ElementTree as ET
import argparse
import json
import re

ROOT = Path(__file__).resolve().parents[2]
THEME = ROOT / 'src/Avalonia.Themes.MacOS'
X = '{http://schemas.microsoft.com/winfx/2006/xaml}'
TYPES = {
    'Double': 'double', 'Int32': 'int', 'Boolean': 'bool',
    'Color': 'global::Avalonia.Media.Color',
    'SolidColorBrush': 'global::Avalonia.Media.IBrush', 'VisualBrush': 'global::Avalonia.Media.IBrush',
    'Thickness': 'global::Avalonia.Thickness', 'CornerRadius': 'global::Avalonia.CornerRadius',
    'FontFamily': 'global::Avalonia.Media.FontFamily', 'FontWeight': 'global::Avalonia.Media.FontWeight',
    'GridLength': 'global::Avalonia.Controls.GridLength', 'PlacementMode': 'global::Avalonia.Controls.PlacementMode',
    'TimeSpan': 'global::System.TimeSpan',
    'TransformOperations': 'global::Avalonia.Media.Transformation.TransformOperations',
}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail on drift without modifying files')
    args = parser.parse_args()
    manifest_path = THEME / 'Tokens/token-manifest.json'
    manifest = json.loads(manifest_path.read_text())
    previous = {entry['key']: entry for entry in manifest['tokens']}
    kinds, aliases, origins = {}, {}, {}
    for path in sorted(THEME.rglob('*.xaml')):
        for node in ET.parse(path).iter():
            key, kind = node.get(X + 'Key', ''), node.tag.rsplit('}', 1)[-1]
            if not key.startswith('MacOS.'):
                continue
            origins.setdefault(key, set()).add(path.relative_to(THEME).as_posix())
            if kind in TYPES:
                if key in kinds and TYPES[kinds[key]] != TYPES[kind]:
                    raise ValueError('Conflicting CLR types for ' + key)
                kinds[key] = kind
            elif kind == 'StaticResource':
                aliases[key] = node.get('ResourceKey')
    for suffix in ('', 'Dark1', 'Dark2', 'Dark3', 'Light1', 'Light2', 'Light3'):
        key = 'MacOS.SystemAccentColor' + suffix
        kinds[key] = 'Color'
        origins.setdefault(key, set()).add('Accents/SystemAccentColors.cs')
    for _ in range(len(aliases) + 1):
        changed = False
        for key, target in aliases.items():
            if key not in kinds and target in kinds:
                kinds[key] = kinds[target]
                changed = True
        if not changed:
            break
    unresolved = set(aliases) - set(kinds)
    if unresolved:
        raise ValueError('Unresolved aliases: ' + ', '.join(sorted(unresolved)))
    removed = set(previous) - set(kinds)
    if removed:
        raise ValueError('Removing a public token requires an explicit API migration: ' + ', '.join(sorted(removed)))
    entries = []
    for key, kind in sorted(kinds.items()):
        entry = dict(previous.get(key, {'key': key, 'legacyKey': None, 'baselineDefinitions': []}))
        if key in previous and TYPES[previous[key]['type']] != TYPES[kind]:
            raise ValueError('Changing a public token CLR type requires an API migration: ' + key)
        entry['type'] = kind
        entry['sources'] = sorted(origins[key])
        entries.append(entry)
    manifest['tokens'] = entries
    optional = []
    for path in sorted((ROOT / 'src/Avalonia.Controls.ColorPicker/Themes/MacOS').glob('*.xaml')):
        for node in ET.parse(path).iter():
            key = node.get(X + 'Key', '')
            if key.startswith('{x:Type '):
                optional.append({'type': key[8:-1], 'source': path.relative_to(ROOT).as_posix()})
    manifest['optionalControls'] = {'Avalonia.Controls.ColorPicker': optional}
    outputs = {manifest_path: json.dumps(manifest, indent=2) + '\n'}
    identifiers = set()
    for legacy, filename in ((True, 'MacOSTokens.g.cs'), (False, 'MacOSTokens.Semantic.g.cs')):
        code = ['// <auto-generated by eng/macos26/update-tokens.py />', '#nullable enable',
                'namespace Avalonia.Themes.MacOS;', '', '/// <summary>Stable, strongly typed visual resource keys.</summary>',
                'public static partial class MacOSTokens', '{']
        for entry in entries:
            if (entry['legacyKey'] is not None) != legacy:
                continue
            name = entry['legacyKey'] or entry['key'].removeprefix('MacOS.')
            identifier = re.sub(r'\W', '_', name)
            if identifier[0].isdigit():
                identifier = '_' + identifier
            if identifier in identifiers:
                raise ValueError('Conflicting public C# identifier: ' + identifier)
            identifiers.add(identifier)
            code += [f'    /// <summary>Overrides {entry["key"]}.</summary>',
                     f'    public static readonly MacOSToken<{TYPES[entry["type"]]}> {identifier} = new("{entry["key"]}");']
        code.append('}')
        outputs[THEME / filename] = '\n'.join(code) + '\n'
    drift = []
    for path, text in outputs.items():
        if not path.exists() or path.read_text() != text:
            drift.append(path.relative_to(ROOT).as_posix())
            if not args.check:
                path.write_text(text)
    if args.check and drift:
        raise SystemExit('Token contract drift; run python3 eng/macos26/update-tokens.py:\n' + '\n'.join(drift))
    print(f'{"Verified" if args.check else "Generated"} {len(entries)} typed tokens and {len(optional)} optional control contracts.')

if __name__ == '__main__':
    main()
