// <auto-generated by eng/macos26/update-tokens.py />
#nullable enable
namespace Avalonia.Themes.MacOS;

/// <summary>Stable, strongly typed visual resource keys.</summary>
public static partial class MacOSTokens
{
    /// <summary>Overrides MacOS.Brush.Accent.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Accent = new("MacOS.Brush.Accent");
    /// <summary>Overrides MacOS.Brush.Control.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Control = new("MacOS.Brush.Control");
    /// <summary>Overrides MacOS.Brush.ControlDisabled.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_ControlDisabled = new("MacOS.Brush.ControlDisabled");
    /// <summary>Overrides MacOS.Brush.ControlHover.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_ControlHover = new("MacOS.Brush.ControlHover");
    /// <summary>Overrides MacOS.Brush.ControlPressed.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_ControlPressed = new("MacOS.Brush.ControlPressed");
    /// <summary>Overrides MacOS.Brush.ControlStroke.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_ControlStroke = new("MacOS.Brush.ControlStroke");
    /// <summary>Overrides MacOS.Brush.Destructive.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Destructive = new("MacOS.Brush.Destructive");
    /// <summary>Overrides MacOS.Brush.DisabledLabel.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_DisabledLabel = new("MacOS.Brush.DisabledLabel");
    /// <summary>Overrides MacOS.Brush.Hover.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Hover = new("MacOS.Brush.Hover");
    /// <summary>Overrides MacOS.Brush.Knob.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Knob = new("MacOS.Brush.Knob");
    /// <summary>Overrides MacOS.Brush.Label.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Label = new("MacOS.Brush.Label");
    /// <summary>Overrides MacOS.Brush.Material.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Material = new("MacOS.Brush.Material");
    /// <summary>Overrides MacOS.Brush.MaterialOpaque.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_MaterialOpaque = new("MacOS.Brush.MaterialOpaque");
    /// <summary>Overrides MacOS.Brush.OnAccent.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_OnAccent = new("MacOS.Brush.OnAccent");
    /// <summary>Overrides MacOS.Brush.SecondaryLabel.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_SecondaryLabel = new("MacOS.Brush.SecondaryLabel");
    /// <summary>Overrides MacOS.Brush.SelectionInactive.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_SelectionInactive = new("MacOS.Brush.SelectionInactive");
    /// <summary>Overrides MacOS.Brush.Separator.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Separator = new("MacOS.Brush.Separator");
    /// <summary>Overrides MacOS.Brush.Success.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Success = new("MacOS.Brush.Success");
    /// <summary>Overrides MacOS.Brush.Surface.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Surface = new("MacOS.Brush.Surface");
    /// <summary>Overrides MacOS.Brush.Track.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Track = new("MacOS.Brush.Track");
    /// <summary>Overrides MacOS.Brush.Transparent.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Transparent = new("MacOS.Brush.Transparent");
    /// <summary>Overrides MacOS.Brush.Warning.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Warning = new("MacOS.Brush.Warning");
    /// <summary>Overrides MacOS.Brush.Window.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Window = new("MacOS.Brush.Window");
    /// <summary>Overrides MacOS.CheckBox.GlyphSize.</summary>
    public static readonly MacOSToken<double> CheckBox_GlyphSize = new("MacOS.CheckBox.GlyphSize");
    /// <summary>Overrides MacOS.CheckBox.Radius.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> CheckBox_Radius = new("MacOS.CheckBox.Radius");
    /// <summary>Overrides MacOS.CheckBox.Size.</summary>
    public static readonly MacOSToken<double> CheckBox_Size = new("MacOS.CheckBox.Size");
    /// <summary>Overrides MacOS.Color.Accent.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Accent = new("MacOS.Color.Accent");
    /// <summary>Overrides MacOS.Color.Control.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Control = new("MacOS.Color.Control");
    /// <summary>Overrides MacOS.Color.ControlDisabled.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_ControlDisabled = new("MacOS.Color.ControlDisabled");
    /// <summary>Overrides MacOS.Color.ControlHover.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_ControlHover = new("MacOS.Color.ControlHover");
    /// <summary>Overrides MacOS.Color.ControlPressed.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_ControlPressed = new("MacOS.Color.ControlPressed");
    /// <summary>Overrides MacOS.Color.ControlStroke.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_ControlStroke = new("MacOS.Color.ControlStroke");
    /// <summary>Overrides MacOS.Color.Destructive.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Destructive = new("MacOS.Color.Destructive");
    /// <summary>Overrides MacOS.Color.DisabledLabel.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_DisabledLabel = new("MacOS.Color.DisabledLabel");
    /// <summary>Overrides MacOS.Color.Hover.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Hover = new("MacOS.Color.Hover");
    /// <summary>Overrides MacOS.Color.Knob.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Knob = new("MacOS.Color.Knob");
    /// <summary>Overrides MacOS.Color.Label.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Label = new("MacOS.Color.Label");
    /// <summary>Overrides MacOS.Color.Material.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Material = new("MacOS.Color.Material");
    /// <summary>Overrides MacOS.Color.MaterialOpaque.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_MaterialOpaque = new("MacOS.Color.MaterialOpaque");
    /// <summary>Overrides MacOS.Color.OnAccent.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_OnAccent = new("MacOS.Color.OnAccent");
    /// <summary>Overrides MacOS.Color.SecondaryLabel.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_SecondaryLabel = new("MacOS.Color.SecondaryLabel");
    /// <summary>Overrides MacOS.Color.SelectionInactive.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_SelectionInactive = new("MacOS.Color.SelectionInactive");
    /// <summary>Overrides MacOS.Color.Separator.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Separator = new("MacOS.Color.Separator");
    /// <summary>Overrides MacOS.Color.Success.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Success = new("MacOS.Color.Success");
    /// <summary>Overrides MacOS.Color.Surface.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Surface = new("MacOS.Color.Surface");
    /// <summary>Overrides MacOS.Color.Track.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Track = new("MacOS.Color.Track");
    /// <summary>Overrides MacOS.Color.Transparent.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Transparent = new("MacOS.Color.Transparent");
    /// <summary>Overrides MacOS.Color.Warning.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Warning = new("MacOS.Color.Warning");
    /// <summary>Overrides MacOS.Color.Window.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Window = new("MacOS.Color.Window");
    /// <summary>Overrides MacOS.ColorPicker.ColorControlCheckeredBackgroundBrush.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> ColorPicker_ColorControlCheckeredBackgroundBrush = new("MacOS.ColorPicker.ColorControlCheckeredBackgroundBrush");
    /// <summary>Overrides MacOS.ColorPicker.ColorControlDarkSelectorBrush.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> ColorPicker_ColorControlDarkSelectorBrush = new("MacOS.ColorPicker.ColorControlDarkSelectorBrush");
    /// <summary>Overrides MacOS.ColorPicker.ColorControlLightSelectorBrush.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> ColorPicker_ColorControlLightSelectorBrush = new("MacOS.ColorPicker.ColorControlLightSelectorBrush");
    /// <summary>Overrides MacOS.ColorPicker.ColorPickerFlyoutPlacement.</summary>
    public static readonly MacOSToken<global::Avalonia.Controls.PlacementMode> ColorPicker_ColorPickerFlyoutPlacement = new("MacOS.ColorPicker.ColorPickerFlyoutPlacement");
    /// <summary>Overrides MacOS.ColorPicker.ColorPreviewerAccentSectionHeight.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorPreviewerAccentSectionHeight = new("MacOS.ColorPicker.ColorPreviewerAccentSectionHeight");
    /// <summary>Overrides MacOS.ColorPicker.ColorPreviewerAccentSectionWidth.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorPreviewerAccentSectionWidth = new("MacOS.ColorPicker.ColorPreviewerAccentSectionWidth");
    /// <summary>Overrides MacOS.ColorPicker.ColorSliderCornerRadius.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> ColorPicker_ColorSliderCornerRadius = new("MacOS.ColorPicker.ColorSliderCornerRadius");
    /// <summary>Overrides MacOS.ColorPicker.ColorSliderSize.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorSliderSize = new("MacOS.ColorPicker.ColorSliderSize");
    /// <summary>Overrides MacOS.ColorPicker.ColorSliderTrackCornerRadius.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> ColorPicker_ColorSliderTrackCornerRadius = new("MacOS.ColorPicker.ColorSliderTrackCornerRadius");
    /// <summary>Overrides MacOS.ColorPicker.ColorSliderTrackSize.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorSliderTrackSize = new("MacOS.ColorPicker.ColorSliderTrackSize");
    /// <summary>Overrides MacOS.ColorPicker.ColorViewComponentLabelWidth.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorViewComponentLabelWidth = new("MacOS.ColorPicker.ColorViewComponentLabelWidth");
    /// <summary>Overrides MacOS.ColorPicker.ColorViewComponentTextInputWidth.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorViewComponentTextInputWidth = new("MacOS.ColorPicker.ColorViewComponentTextInputWidth");
    /// <summary>Overrides MacOS.ColorPicker.ColorViewContentBackgroundBrush.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> ColorPicker_ColorViewContentBackgroundBrush = new("MacOS.ColorPicker.ColorViewContentBackgroundBrush");
    /// <summary>Overrides MacOS.ColorPicker.ColorViewContentBorderBrush.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> ColorPicker_ColorViewContentBorderBrush = new("MacOS.ColorPicker.ColorViewContentBorderBrush");
    /// <summary>Overrides MacOS.ColorPicker.ColorViewTabBackgroundCornerRadius.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> ColorPicker_ColorViewTabBackgroundCornerRadius = new("MacOS.ColorPicker.ColorViewTabBackgroundCornerRadius");
    /// <summary>Overrides MacOS.ColorPicker.ColorViewTabBorderBrush.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> ColorPicker_ColorViewTabBorderBrush = new("MacOS.ColorPicker.ColorViewTabBorderBrush");
    /// <summary>Overrides MacOS.ColorPicker.ColorViewTabStripHeight.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorViewTabStripHeight = new("MacOS.ColorPicker.ColorViewTabStripHeight");
    /// <summary>Overrides MacOS.ColorPicker.FlyoutTabBackgroundCornerRadius.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> ColorPicker_FlyoutTabBackgroundCornerRadius = new("MacOS.ColorPicker.FlyoutTabBackgroundCornerRadius");
    /// <summary>Overrides MacOS.Focus.Radius.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> Focus_Radius = new("MacOS.Focus.Radius");
    /// <summary>Overrides MacOS.Motion.Interaction.</summary>
    public static readonly MacOSToken<global::System.TimeSpan> Motion_Interaction = new("MacOS.Motion.Interaction");
    /// <summary>Overrides MacOS.Motion.Switch.</summary>
    public static readonly MacOSToken<global::System.TimeSpan> Motion_Switch = new("MacOS.Motion.Switch");
    /// <summary>Overrides MacOS.RadioButton.GlyphSize.</summary>
    public static readonly MacOSToken<double> RadioButton_GlyphSize = new("MacOS.RadioButton.GlyphSize");
    /// <summary>Overrides MacOS.RadioButton.Size.</summary>
    public static readonly MacOSToken<double> RadioButton_Size = new("MacOS.RadioButton.Size");
    /// <summary>Overrides MacOS.Selection.Margin.</summary>
    public static readonly MacOSToken<global::Avalonia.Thickness> Selection_Margin = new("MacOS.Selection.Margin");
    /// <summary>Overrides MacOS.Selection.Radius.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> Selection_Radius = new("MacOS.Selection.Radius");
    /// <summary>Overrides MacOS.Slider.ThumbStroke.</summary>
    public static readonly MacOSToken<global::Avalonia.Thickness> Slider_ThumbStroke = new("MacOS.Slider.ThumbStroke");
    /// <summary>Overrides MacOS.Stepper.ButtonHeight.</summary>
    public static readonly MacOSToken<double> Stepper_ButtonHeight = new("MacOS.Stepper.ButtonHeight");
    /// <summary>Overrides MacOS.Stepper.IconHeight.</summary>
    public static readonly MacOSToken<double> Stepper_IconHeight = new("MacOS.Stepper.IconHeight");
    /// <summary>Overrides MacOS.Stepper.IconWidth.</summary>
    public static readonly MacOSToken<double> Stepper_IconWidth = new("MacOS.Stepper.IconWidth");
    /// <summary>Overrides MacOS.Stepper.Margin.</summary>
    public static readonly MacOSToken<global::Avalonia.Thickness> Stepper_Margin = new("MacOS.Stepper.Margin");
    /// <summary>Overrides MacOS.Stepper.Width.</summary>
    public static readonly MacOSToken<double> Stepper_Width = new("MacOS.Stepper.Width");
    /// <summary>Overrides MacOS.Switch.KnobSize.</summary>
    public static readonly MacOSToken<double> Switch_KnobSize = new("MacOS.Switch.KnobSize");
    /// <summary>Overrides MacOS.Switch.Radius.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> Switch_Radius = new("MacOS.Switch.Radius");
    /// <summary>Overrides MacOS.Switch.TrackHeight.</summary>
    public static readonly MacOSToken<double> Switch_TrackHeight = new("MacOS.Switch.TrackHeight");
    /// <summary>Overrides MacOS.Switch.TrackWidth.</summary>
    public static readonly MacOSToken<double> Switch_TrackWidth = new("MacOS.Switch.TrackWidth");
    /// <summary>Overrides MacOS.Switch.Travel.</summary>
    public static readonly MacOSToken<double> Switch_Travel = new("MacOS.Switch.Travel");
}
