// <auto-generated />
#nullable enable
namespace Avalonia.Themes.MacOS;

public static partial class MacOSTokens
{
    /// <summary>Gets the MacOS.Brush.Accent token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Accent = new("MacOS.Brush.Accent");
    /// <summary>Gets the MacOS.Brush.Control token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Control = new("MacOS.Brush.Control");
    /// <summary>Gets the MacOS.Brush.ControlDisabled token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_ControlDisabled = new("MacOS.Brush.ControlDisabled");
    /// <summary>Gets the MacOS.Brush.ControlHover token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_ControlHover = new("MacOS.Brush.ControlHover");
    /// <summary>Gets the MacOS.Brush.ControlPressed token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_ControlPressed = new("MacOS.Brush.ControlPressed");
    /// <summary>Gets the MacOS.Brush.ControlStroke token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_ControlStroke = new("MacOS.Brush.ControlStroke");
    /// <summary>Gets the MacOS.Brush.Destructive token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Destructive = new("MacOS.Brush.Destructive");
    /// <summary>Gets the MacOS.Brush.DisabledLabel token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_DisabledLabel = new("MacOS.Brush.DisabledLabel");
    /// <summary>Gets the MacOS.Brush.Hover token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Hover = new("MacOS.Brush.Hover");
    /// <summary>Gets the MacOS.Brush.Knob token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Knob = new("MacOS.Brush.Knob");
    /// <summary>Gets the MacOS.Brush.Label token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Label = new("MacOS.Brush.Label");
    /// <summary>Gets the MacOS.Brush.Material token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Material = new("MacOS.Brush.Material");
    /// <summary>Gets the MacOS.Brush.MaterialOpaque token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_MaterialOpaque = new("MacOS.Brush.MaterialOpaque");
    /// <summary>Gets the MacOS.Brush.OnAccent token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_OnAccent = new("MacOS.Brush.OnAccent");
    /// <summary>Gets the MacOS.Brush.SecondaryLabel token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_SecondaryLabel = new("MacOS.Brush.SecondaryLabel");
    /// <summary>Gets the MacOS.Brush.SelectionInactive token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_SelectionInactive = new("MacOS.Brush.SelectionInactive");
    /// <summary>Gets the MacOS.Brush.Separator token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Separator = new("MacOS.Brush.Separator");
    /// <summary>Gets the MacOS.Brush.Success token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Success = new("MacOS.Brush.Success");
    /// <summary>Gets the MacOS.Brush.Surface token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Surface = new("MacOS.Brush.Surface");
    /// <summary>Gets the MacOS.Brush.Track token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Track = new("MacOS.Brush.Track");
    /// <summary>Gets the MacOS.Brush.Transparent token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Transparent = new("MacOS.Brush.Transparent");
    /// <summary>Gets the MacOS.Brush.Warning token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Warning = new("MacOS.Brush.Warning");
    /// <summary>Gets the MacOS.Brush.Window token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Window = new("MacOS.Brush.Window");
    /// <summary>Gets the MacOS.CheckBox.GlyphSize token.</summary>
    public static readonly MacOSToken<double> CheckBox_GlyphSize = new("MacOS.CheckBox.GlyphSize");
    /// <summary>Gets the MacOS.CheckBox.Radius token.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> CheckBox_Radius = new("MacOS.CheckBox.Radius");
    /// <summary>Gets the MacOS.CheckBox.Size token.</summary>
    public static readonly MacOSToken<double> CheckBox_Size = new("MacOS.CheckBox.Size");
    /// <summary>Gets the MacOS.Color.Accent token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Accent = new("MacOS.Color.Accent");
    /// <summary>Gets the MacOS.Color.Control token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Control = new("MacOS.Color.Control");
    /// <summary>Gets the MacOS.Color.ControlDisabled token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_ControlDisabled = new("MacOS.Color.ControlDisabled");
    /// <summary>Gets the MacOS.Color.ControlHover token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_ControlHover = new("MacOS.Color.ControlHover");
    /// <summary>Gets the MacOS.Color.ControlPressed token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_ControlPressed = new("MacOS.Color.ControlPressed");
    /// <summary>Gets the MacOS.Color.ControlStroke token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_ControlStroke = new("MacOS.Color.ControlStroke");
    /// <summary>Gets the MacOS.Color.Destructive token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Destructive = new("MacOS.Color.Destructive");
    /// <summary>Gets the MacOS.Color.DisabledLabel token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_DisabledLabel = new("MacOS.Color.DisabledLabel");
    /// <summary>Gets the MacOS.Color.Hover token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Hover = new("MacOS.Color.Hover");
    /// <summary>Gets the MacOS.Color.Knob token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Knob = new("MacOS.Color.Knob");
    /// <summary>Gets the MacOS.Color.Label token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Label = new("MacOS.Color.Label");
    /// <summary>Gets the MacOS.Color.Material token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Material = new("MacOS.Color.Material");
    /// <summary>Gets the MacOS.Color.MaterialOpaque token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_MaterialOpaque = new("MacOS.Color.MaterialOpaque");
    /// <summary>Gets the MacOS.Color.OnAccent token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_OnAccent = new("MacOS.Color.OnAccent");
    /// <summary>Gets the MacOS.Color.SecondaryLabel token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_SecondaryLabel = new("MacOS.Color.SecondaryLabel");
    /// <summary>Gets the MacOS.Color.SelectionInactive token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_SelectionInactive = new("MacOS.Color.SelectionInactive");
    /// <summary>Gets the MacOS.Color.Separator token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Separator = new("MacOS.Color.Separator");
    /// <summary>Gets the MacOS.Color.Success token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Success = new("MacOS.Color.Success");
    /// <summary>Gets the MacOS.Color.Surface token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Surface = new("MacOS.Color.Surface");
    /// <summary>Gets the MacOS.Color.Track token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Track = new("MacOS.Color.Track");
    /// <summary>Gets the MacOS.Color.Transparent token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Transparent = new("MacOS.Color.Transparent");
    /// <summary>Gets the MacOS.Color.Warning token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Warning = new("MacOS.Color.Warning");
    /// <summary>Gets the MacOS.Color.Window token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Window = new("MacOS.Color.Window");
    /// <summary>Gets the MacOS.ColorPicker.ColorControlCheckeredBackgroundBrush token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> ColorPicker_ColorControlCheckeredBackgroundBrush = new("MacOS.ColorPicker.ColorControlCheckeredBackgroundBrush");
    /// <summary>Gets the MacOS.ColorPicker.ColorControlDarkSelectorBrush token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> ColorPicker_ColorControlDarkSelectorBrush = new("MacOS.ColorPicker.ColorControlDarkSelectorBrush");
    /// <summary>Gets the MacOS.ColorPicker.ColorControlLightSelectorBrush token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> ColorPicker_ColorControlLightSelectorBrush = new("MacOS.ColorPicker.ColorControlLightSelectorBrush");
    /// <summary>Gets the MacOS.ColorPicker.ColorPickerFlyoutPlacement token.</summary>
    public static readonly MacOSToken<global::Avalonia.Controls.PlacementMode> ColorPicker_ColorPickerFlyoutPlacement = new("MacOS.ColorPicker.ColorPickerFlyoutPlacement");
    /// <summary>Gets the MacOS.ColorPicker.ColorPreviewerAccentSectionHeight token.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorPreviewerAccentSectionHeight = new("MacOS.ColorPicker.ColorPreviewerAccentSectionHeight");
    /// <summary>Gets the MacOS.ColorPicker.ColorPreviewerAccentSectionWidth token.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorPreviewerAccentSectionWidth = new("MacOS.ColorPicker.ColorPreviewerAccentSectionWidth");
    /// <summary>Gets the MacOS.ColorPicker.ColorSliderCornerRadius token.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> ColorPicker_ColorSliderCornerRadius = new("MacOS.ColorPicker.ColorSliderCornerRadius");
    /// <summary>Gets the MacOS.ColorPicker.ColorSliderSize token.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorSliderSize = new("MacOS.ColorPicker.ColorSliderSize");
    /// <summary>Gets the MacOS.ColorPicker.ColorSliderTrackCornerRadius token.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> ColorPicker_ColorSliderTrackCornerRadius = new("MacOS.ColorPicker.ColorSliderTrackCornerRadius");
    /// <summary>Gets the MacOS.ColorPicker.ColorSliderTrackSize token.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorSliderTrackSize = new("MacOS.ColorPicker.ColorSliderTrackSize");
    /// <summary>Gets the MacOS.ColorPicker.ColorViewComponentLabelWidth token.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorViewComponentLabelWidth = new("MacOS.ColorPicker.ColorViewComponentLabelWidth");
    /// <summary>Gets the MacOS.ColorPicker.ColorViewComponentTextInputWidth token.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorViewComponentTextInputWidth = new("MacOS.ColorPicker.ColorViewComponentTextInputWidth");
    /// <summary>Gets the MacOS.ColorPicker.ColorViewContentBackgroundBrush token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> ColorPicker_ColorViewContentBackgroundBrush = new("MacOS.ColorPicker.ColorViewContentBackgroundBrush");
    /// <summary>Gets the MacOS.ColorPicker.ColorViewContentBorderBrush token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> ColorPicker_ColorViewContentBorderBrush = new("MacOS.ColorPicker.ColorViewContentBorderBrush");
    /// <summary>Gets the MacOS.ColorPicker.ColorViewTabBackgroundCornerRadius token.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> ColorPicker_ColorViewTabBackgroundCornerRadius = new("MacOS.ColorPicker.ColorViewTabBackgroundCornerRadius");
    /// <summary>Gets the MacOS.ColorPicker.ColorViewTabBorderBrush token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> ColorPicker_ColorViewTabBorderBrush = new("MacOS.ColorPicker.ColorViewTabBorderBrush");
    /// <summary>Gets the MacOS.ColorPicker.ColorViewTabStripHeight token.</summary>
    public static readonly MacOSToken<double> ColorPicker_ColorViewTabStripHeight = new("MacOS.ColorPicker.ColorViewTabStripHeight");
    /// <summary>Gets the MacOS.ColorPicker.FlyoutTabBackgroundCornerRadius token.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> ColorPicker_FlyoutTabBackgroundCornerRadius = new("MacOS.ColorPicker.FlyoutTabBackgroundCornerRadius");
    /// <summary>Gets the MacOS.Focus.Radius token.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> Focus_Radius = new("MacOS.Focus.Radius");
    /// <summary>Gets the MacOS.Motion.Interaction token.</summary>
    public static readonly MacOSToken<global::System.TimeSpan> Motion_Interaction = new("MacOS.Motion.Interaction");
    /// <summary>Gets the MacOS.Motion.Switch token.</summary>
    public static readonly MacOSToken<global::System.TimeSpan> Motion_Switch = new("MacOS.Motion.Switch");
    /// <summary>Gets the MacOS.RadioButton.GlyphSize token.</summary>
    public static readonly MacOSToken<double> RadioButton_GlyphSize = new("MacOS.RadioButton.GlyphSize");
    /// <summary>Gets the MacOS.RadioButton.Size token.</summary>
    public static readonly MacOSToken<double> RadioButton_Size = new("MacOS.RadioButton.Size");
    /// <summary>Gets the MacOS.Selection.Margin token.</summary>
    public static readonly MacOSToken<global::Avalonia.Thickness> Selection_Margin = new("MacOS.Selection.Margin");
    /// <summary>Gets the MacOS.Selection.Radius token.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> Selection_Radius = new("MacOS.Selection.Radius");
    /// <summary>Gets the MacOS.Slider.ThumbStroke token.</summary>
    public static readonly MacOSToken<global::Avalonia.Thickness> Slider_ThumbStroke = new("MacOS.Slider.ThumbStroke");
    /// <summary>Gets the MacOS.Stepper.ButtonHeight token.</summary>
    public static readonly MacOSToken<double> Stepper_ButtonHeight = new("MacOS.Stepper.ButtonHeight");
    /// <summary>Gets the MacOS.Stepper.IconHeight token.</summary>
    public static readonly MacOSToken<double> Stepper_IconHeight = new("MacOS.Stepper.IconHeight");
    /// <summary>Gets the MacOS.Stepper.IconWidth token.</summary>
    public static readonly MacOSToken<double> Stepper_IconWidth = new("MacOS.Stepper.IconWidth");
    /// <summary>Gets the MacOS.Stepper.Margin token.</summary>
    public static readonly MacOSToken<global::Avalonia.Thickness> Stepper_Margin = new("MacOS.Stepper.Margin");
    /// <summary>Gets the MacOS.Stepper.Width token.</summary>
    public static readonly MacOSToken<double> Stepper_Width = new("MacOS.Stepper.Width");
    /// <summary>Gets the MacOS.Switch.KnobSize token.</summary>
    public static readonly MacOSToken<double> Switch_KnobSize = new("MacOS.Switch.KnobSize");
    /// <summary>Gets the MacOS.Switch.Radius token.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> Switch_Radius = new("MacOS.Switch.Radius");
    /// <summary>Gets the MacOS.Switch.TrackHeight token.</summary>
    public static readonly MacOSToken<double> Switch_TrackHeight = new("MacOS.Switch.TrackHeight");
    /// <summary>Gets the MacOS.Switch.TrackWidth token.</summary>
    public static readonly MacOSToken<double> Switch_TrackWidth = new("MacOS.Switch.TrackWidth");
    /// <summary>Gets the MacOS.Switch.Travel token.</summary>
    public static readonly MacOSToken<double> Switch_Travel = new("MacOS.Switch.Travel");
}
