// <auto-generated />
#nullable enable
namespace Avalonia.Themes.MacOS;

public static partial class MacOSTokens
{
    /// <summary>Gets the MacOS.Brush.Control token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Control = new("MacOS.Brush.Control");
    /// <summary>Gets the MacOS.Brush.ControlDisabled token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_ControlDisabled = new("MacOS.Brush.ControlDisabled");
    /// <summary>Gets the MacOS.Brush.ControlHover token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_ControlHover = new("MacOS.Brush.ControlHover");
    /// <summary>Gets the MacOS.Brush.ControlPressed token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_ControlPressed = new("MacOS.Brush.ControlPressed");
    /// <summary>Gets the MacOS.Brush.ControlStroke token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_ControlStroke = new("MacOS.Brush.ControlStroke");
    /// <summary>Gets the MacOS.Brush.Destructive token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Destructive = new("MacOS.Brush.Destructive");
    /// <summary>Gets the MacOS.Brush.DisabledLabel token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_DisabledLabel = new("MacOS.Brush.DisabledLabel");
    /// <summary>Gets the MacOS.Brush.Hover token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Hover = new("MacOS.Brush.Hover");
    /// <summary>Gets the MacOS.Brush.Knob token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Knob = new("MacOS.Brush.Knob");
    /// <summary>Gets the MacOS.Brush.Label token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Label = new("MacOS.Brush.Label");
    /// <summary>Gets the MacOS.Brush.Material token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Material = new("MacOS.Brush.Material");
    /// <summary>Gets the MacOS.Brush.MaterialOpaque token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_MaterialOpaque = new("MacOS.Brush.MaterialOpaque");
    /// <summary>Gets the MacOS.Brush.OnAccent token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_OnAccent = new("MacOS.Brush.OnAccent");
    /// <summary>Gets the MacOS.Brush.SecondaryLabel token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_SecondaryLabel = new("MacOS.Brush.SecondaryLabel");
    /// <summary>Gets the MacOS.Brush.SelectionInactive token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_SelectionInactive = new("MacOS.Brush.SelectionInactive");
    /// <summary>Gets the MacOS.Brush.Separator token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Separator = new("MacOS.Brush.Separator");
    /// <summary>Gets the MacOS.Brush.Success token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Success = new("MacOS.Brush.Success");
    /// <summary>Gets the MacOS.Brush.Surface token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Surface = new("MacOS.Brush.Surface");
    /// <summary>Gets the MacOS.Brush.Track token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Track = new("MacOS.Brush.Track");
    /// <summary>Gets the MacOS.Brush.Transparent token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Transparent = new("MacOS.Brush.Transparent");
    /// <summary>Gets the MacOS.Brush.Warning token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Warning = new("MacOS.Brush.Warning");
    /// <summary>Gets the MacOS.Brush.Window token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.IBrush> Brush_Window = new("MacOS.Brush.Window");
    /// <summary>Gets the MacOS.Color.Control token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Control = new("MacOS.Color.Control");
    /// <summary>Gets the MacOS.Color.ControlDisabled token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_ControlDisabled = new("MacOS.Color.ControlDisabled");
    /// <summary>Gets the MacOS.Color.ControlHover token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_ControlHover = new("MacOS.Color.ControlHover");
    /// <summary>Gets the MacOS.Color.ControlPressed token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_ControlPressed = new("MacOS.Color.ControlPressed");
    /// <summary>Gets the MacOS.Color.ControlStroke token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_ControlStroke = new("MacOS.Color.ControlStroke");
    /// <summary>Gets the MacOS.Color.Destructive token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Destructive = new("MacOS.Color.Destructive");
    /// <summary>Gets the MacOS.Color.DisabledLabel token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_DisabledLabel = new("MacOS.Color.DisabledLabel");
    /// <summary>Gets the MacOS.Color.Hover token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Hover = new("MacOS.Color.Hover");
    /// <summary>Gets the MacOS.Color.Knob token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Knob = new("MacOS.Color.Knob");
    /// <summary>Gets the MacOS.Color.Label token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Label = new("MacOS.Color.Label");
    /// <summary>Gets the MacOS.Color.Material token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Material = new("MacOS.Color.Material");
    /// <summary>Gets the MacOS.Color.MaterialOpaque token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_MaterialOpaque = new("MacOS.Color.MaterialOpaque");
    /// <summary>Gets the MacOS.Color.OnAccent token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_OnAccent = new("MacOS.Color.OnAccent");
    /// <summary>Gets the MacOS.Color.SecondaryLabel token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_SecondaryLabel = new("MacOS.Color.SecondaryLabel");
    /// <summary>Gets the MacOS.Color.SelectionInactive token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_SelectionInactive = new("MacOS.Color.SelectionInactive");
    /// <summary>Gets the MacOS.Color.Separator token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Separator = new("MacOS.Color.Separator");
    /// <summary>Gets the MacOS.Color.Success token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Success = new("MacOS.Color.Success");
    /// <summary>Gets the MacOS.Color.Surface token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Surface = new("MacOS.Color.Surface");
    /// <summary>Gets the MacOS.Color.Track token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Track = new("MacOS.Color.Track");
    /// <summary>Gets the MacOS.Color.Transparent token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Transparent = new("MacOS.Color.Transparent");
    /// <summary>Gets the MacOS.Color.Warning token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Warning = new("MacOS.Color.Warning");
    /// <summary>Gets the MacOS.Color.Window token.</summary>
    public static readonly MacOSToken<global::Avalonia.Media.Color> Color_Window = new("MacOS.Color.Window");
    /// <summary>Gets the MacOS.Focus.Radius token.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> Focus_Radius = new("MacOS.Focus.Radius");
    /// <summary>Gets the MacOS.Motion.Interaction token.</summary>
    public static readonly MacOSToken<global::System.TimeSpan> Motion_Interaction = new("MacOS.Motion.Interaction");
    /// <summary>Gets the MacOS.Motion.Switch token.</summary>
    public static readonly MacOSToken<global::System.TimeSpan> Motion_Switch = new("MacOS.Motion.Switch");
    /// <summary>Gets the MacOS.Selection.Radius token.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> Selection_Radius = new("MacOS.Selection.Radius");
    /// <summary>Gets the MacOS.Switch.KnobSize token.</summary>
    public static readonly MacOSToken<double> Switch_KnobSize = new("MacOS.Switch.KnobSize");
    /// <summary>Gets the MacOS.Switch.Radius token.</summary>
    public static readonly MacOSToken<global::Avalonia.CornerRadius> Switch_Radius = new("MacOS.Switch.Radius");
    /// <summary>Gets the MacOS.Switch.TrackHeight token.</summary>
    public static readonly MacOSToken<double> Switch_TrackHeight = new("MacOS.Switch.TrackHeight");
    /// <summary>Gets the MacOS.Switch.TrackWidth token.</summary>
    public static readonly MacOSToken<double> Switch_TrackWidth = new("MacOS.Switch.TrackWidth");
}
